export const viewUsersPermission = "view_users"
export const viewSubculturesPermission = "view_subcultures"
export const viewTagsPermission = "view_tags"
export const viewParsersPermission = "view_parsers"
export const viewVkCompare = "view_vk_compare"
export const viewVkSearch = "view_vk_search"

export const setAdminRolePermission = "set_admin_role"
export const setEditorRolePermission = "set_editor_role"

export const deleteVkGroupPermission = "delete_vk_group"
export const deleteVkUserPermission = "delete_vk_user"
export const deleteTelegramChannelPermission = "delete_telegram_channel"
export const deleteTelegramPostPermission = "delete_telegram_post"
export const deleteTiktokUserPermission = "delete_tiktok_user"
export const deleteTiktokPostPermission = "delete_tiktok_post"
export const deleteTagPermission = "delete_tag"
export const deleteSubculturePermission = "delete_subculture"

export const checkVkGroupPermission = "check_vk_group"
export const checkVkUserPermission = "check_vk_user"
export const checkTelegramChannelPermission = "check_telegram_channel"
export const checkTelegramPostPermission = "check_telegram_post"
export const checkTiktokUserPermission = "check_tiktok_user"
export const checkTiktokPostPermission = "check_tiktok_post"